# -*- coding: utf-8 -*-
"""Data_Visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o5i8uM9tm9eDsRu-0g0KkQ4KcLSHNLG8
"""

import matplotlib.pyplot as plt
x = [5,7,8,7,12,2,9]

y = [33,100,45,67,36,78,98]

plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
x1 = [89,34,56,75,65,92,24]
y1 = [26,34,90,47,56,89,11]

x2 = [11,32,56,67,54,77,84]
y2 = [26,39,92,48,53,89,11]

plt.scatter(x1,y1,c='green',linewidths = 2,marker = "s",edgecolors="yellow",s = 50)
plt.scatter(x2,y2,c='red',linewidths = 2,marker = "o",edgecolors="blue",s = 30)

plt.xlabel("X-Axis")
plt.ylabel("Y-Axis")

cars = ['Audi','BMW','Ferrari','Jaguar','Mercedes']

data = [23,45,10,12,30,]

fig = plt.figure(figsize = (6,5))
plt.pie(data , labels = cars)

plt.show()

cars = ['Audi','BMW','Ferrari','Jaguar','Mercedes']

data = [23,45,10,12,30]

fig = plt.figure(figsize = (6,5))
plt.pie(data , labels = cars)
plt.legend(title= "Cars")
plt.show()

import numpy as np
x = np.array([3,4,5,6])
y = x*2

''' x = [2,3,5,6]
y = [5,7,8,9]
 '''
plt.plot(x,y)
plt.xlabel("X-Axis")
plt.ylabel("Y-Axis")
plt.title("line graph")
plt.figure()

x1 = [2,3,5,6]
y1 = [5,7,8,9]
plt.plot(x1,y1,'-.',c= "indigo")
plt.title("New graph")
plt.show()

x = np.array([1,2,3,4])
y = x*2
plt.plot(x,y)
x1 = [2,4,6,8]
y1 = [3,5,7,9]

plt.plot(x,y1,'-.')
plt.xlabel("X-Axis")
plt.ylabel("Y-Axis")
plt.title("Multiple plots")
plt.fill_between(x,y,y1,color= 'red',alpha = 0.2)

x = np.array([80, 85, 90, 95, 100, 105])
y = np.array([240, 250, 260, 270, 280, 290])

plt.title("Grid Chart")
plt.xlabel("X-Axis")
plt.ylabel("Y-Axis")

plt.plot(x, y)


plt.grid(axis = 'y',linestyle = '-.',linewidth = 3)

plt.show()

x = np.array([0, 1, 2, 3])
y = np.array([3, 8, 1, 10])

plt.subplot(2, 3, 1)
plt.plot(x,y)

x = np.array([0, 1, 2, 3])
y = np.array([10, 20, 30, 40])


plt.xlabel("X-Axis")
plt.ylabel("Y-Axis")
plt.title("Subplot")
plt.subplot(2, 3, 3)
plt.plot(x,y)

x = np.array(["Apple", "Orange", "Guava", "papaya"])
y = np.array([3, 8, 1, 10])

plt.bar(x, y)
plt.show()

x = np.array(["A", "B", "C", "D"])
y = np.array([3, 8, 1, 10])

plt.barh(x, y)
plt.show()

x = np.array(["A", "B", "C", "D"])
y = np.array([3, 8, 1, 10])

plt.bar(x, y, width =0.4)
plt.show()

x = np.array(["A", "B", "C", "D"])
y = np.array([3, 8, 1, 10])

plt.barh(x, y, height = 0.4,color = "green")
plt.show()



x = [2,3,4,5,6,76,7,8,34,5,56,7,8,6,75,90,34,12,33,44]
y = [74, 78, 59 ,45,40, 24,33,3,47,87,17,22,90,79, 53,3 ,54,66, 96 ,27]

plt.hist(x)
plt.hist(y)
plt.show()

import pandas as pd
db=pd.read_csv(
     "/content/sample_data/california_housing_train.csv"
)
db.head()

x = db["latitude"]
y = db["total_bedrooms"]

plt.plot(x,y)
plt.show()

plt.hist(x)
plt.hist(y)
plt.show()

plt.scatter(x,y)
plt.show()